#!/usr/bin/env node
/**
 * Claw2UI Server
 *
 * An Agent-to-UI bridge that serves interactive pages generated by AI agents.
 * Pages are accessible via tunnel URL even without a public IP.
 *
 * API:
 *   POST /api/pages          - Create a page (JSON body: { html?, spec?, title?, ttl? })
 *   GET  /api/pages          - List all pages
 *   GET  /api/pages/:id      - Get page metadata
 *   DELETE /api/pages/:id    - Delete a page
 *   GET  /api/platforms      - List available format platforms
 *   GET  /api/status         - Server status & public URL
 *   GET  /p/:id              - View a rendered page (public, no auth)
 */
import express, { Request, Response, NextFunction } from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { savePage, getPage, listPages, deletePage } from './store';
import { renderPage, renderRawPage } from './renderer';
import { startTunnel, getPublicUrl, stopTunnel } from './tunnel';
import { formatForAll, listPlatforms } from './platforms';
import { saveToken as storeToken, getToken, listTokens as listAllTokens, revokeToken, findTokenById, checkDailyLimit, recordUsage, countRecentTokensByIp } from './token-store';
import type { PageSpec } from './types';

const PORT = parseInt(process.env.CLAWBOARD_PORT || '9800', 10);
const NO_TUNNEL = process.env.CLAWBOARD_NO_TUNNEL === '1';

// === Security: API Token ===
const TOKEN_FILE = path.join(__dirname, '..', '.api-token');

function getOrCreateToken(): string {
  if (process.env.CLAWBOARD_TOKEN) return process.env.CLAWBOARD_TOKEN;
  if (fs.existsSync(TOKEN_FILE)) return fs.readFileSync(TOKEN_FILE, 'utf-8').trim();
  const token = crypto.randomBytes(32).toString('hex');
  fs.writeFileSync(TOKEN_FILE, token, { mode: 0o600 });
  return token;
}

const API_TOKEN = getOrCreateToken();

/**
 * Load tokens from claw2ui.config.json (admin-managed config tokens)
 */
function loadConfigTokens(): string[] {
  const configPath = path.join(process.cwd(), 'claw2ui.config.json');
  try {
    if (fs.existsSync(configPath)) {
      const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      return Array.isArray(config.tokens) ? config.tokens : [];
    }
  } catch {}
  return [];
}

/**
 * Auth middleware - checks Bearer token.
 * Accepts: admin token, config tokens, or registered (non-disabled) tokens.
 * Mutating operations (POST, DELETE) always require a Bearer token to prevent CSRF.
 */
function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const auth = req.headers.authorization;
  if (auth && auth.startsWith('Bearer ')) {
    const token = auth.slice(7);
    // Check admin token
    if (token === API_TOKEN) { next(); return; }
    // Check config tokens
    if (loadConfigTokens().includes(token)) { next(); return; }
    // Check registered tokens
    const record = getToken(token);
    if (record && !record.disabled) { next(); return; }
  }

  res.status(401).json({ error: 'Unauthorized. Provide Authorization: Bearer <token>' });
}

/**
 * Privileged auth middleware - allows admin token, config tokens, or localhost.
 * Does NOT accept registered (self-service) tokens.
 */
function requirePrivilegedAuth(req: Request, res: Response, next: NextFunction): void {
  const ip = req.ip || '';
  const isLocal = ip === '127.0.0.1' || ip === '::1' || ip === '::ffff:127.0.0.1';
  if (isLocal) { next(); return; }

  const auth = req.headers.authorization;
  if (auth && auth.startsWith('Bearer ')) {
    const token = auth.slice(7);
    if (token === API_TOKEN || loadConfigTokens().includes(token)) {
      next(); return;
    }
  }

  res.status(403).json({ error: 'Insufficient permissions. Admin access required for this endpoint.' });
}

/**
 * Admin auth middleware - only allows admin token or localhost.
 */
function requireAdminAuth(req: Request, res: Response, next: NextFunction): void {
  const ip = req.ip || '';
  const isLocal = ip === '127.0.0.1' || ip === '::1' || ip === '::ffff:127.0.0.1';
  if (isLocal) { next(); return; }

  const auth = req.headers.authorization;
  if (auth && auth.startsWith('Bearer ') && auth.slice(7) === API_TOKEN) {
    next(); return;
  }

  res.status(403).json({ error: 'Admin access required.' });
}

// === Rate Limiting ===
interface RateLimitEntry {
  start: number;
  count: number;
}

const rateLimitMap = new Map<string, RateLimitEntry>();
const RATE_LIMIT_WINDOW = 60_000;
const RATE_LIMIT_MAX = 30;

function rateLimit(req: Request, res: Response, next: NextFunction): void {
  const ip = req.ip || '';
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now - entry.start > RATE_LIMIT_WINDOW) {
    rateLimitMap.set(ip, { start: now, count: 1 });
    next(); return;
  }

  entry.count++;
  if (entry.count > RATE_LIMIT_MAX) {
    res.status(429).json({ error: 'Too many requests. Try again later.' });
    return;
  }
  next();
}

setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of rateLimitMap) {
    if (now - entry.start > RATE_LIMIT_WINDOW) rateLimitMap.delete(ip);
  }
}, RATE_LIMIT_WINDOW);

// === App Setup ===
const app = express();

app.set('trust proxy', 'loopback');

app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(rateLimit);

// Security headers
app.use((_req: Request, res: Response, next: NextFunction) => {
  res.header('X-Content-Type-Options', 'nosniff');
  res.header('X-Frame-Options', 'DENY');
  res.header('Referrer-Policy', 'no-referrer');
  next();
});

// CORS
app.use((req: Request, res: Response, next: NextFunction) => {
  const origin = req.headers.origin || '';
  if (origin.startsWith('http://localhost') || origin.startsWith('http://127.0.0.1')) {
    res.header('Access-Control-Allow-Origin', origin);
  }
  res.header('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') { res.sendStatus(200); return; }
  next();
});

/** Validate page ID format - prevent path traversal */
function isValidPageId(id: string): boolean {
  return /^[A-Za-z0-9_-]{5,30}$/.test(id);
}

/** Extract route param as string (Express 5 params can be string | string[]) */
function paramStr(val: string | string[] | undefined): string {
  if (Array.isArray(val)) return val[0] || '';
  return val || '';
}

function escHtml(s: string): string {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// === Registration Rate Limiting ===
const regRateLimitMap = new Map<string, { start: number; count: number }>();
const REG_RATE_WINDOW = 60_000; // 1 minute
const REG_RATE_MAX = 5;

setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of regRateLimitMap) {
    if (now - entry.start > REG_RATE_WINDOW) regRateLimitMap.delete(ip);
  }
}, REG_RATE_WINDOW);

// === Self-Service Registration (NO auth required) ===

app.post('/api/register', (req: Request, res: Response) => {
  const ip = req.ip || '';

  // Per-minute rate limit
  const now = Date.now();
  const regEntry = regRateLimitMap.get(ip);
  if (regEntry && now - regEntry.start < REG_RATE_WINDOW) {
    regEntry.count++;
    if (regEntry.count > REG_RATE_MAX) {
      res.status(429).json({ error: 'Too many registration attempts. Try again later.' });
      return;
    }
  } else {
    regRateLimitMap.set(ip, { start: now, count: 1 });
  }

  // Max tokens per IP per 24h
  const recentCount = countRecentTokensByIp(ip, 24 * 60 * 60 * 1000);
  if (recentCount >= 3) {
    res.status(429).json({ error: 'Maximum registrations per day reached. Try again tomorrow.' });
    return;
  }

  // Max total active tokens (disabled/revoked tokens don't count)
  const activeCount = listAllTokens().filter(t => !t.disabled).length;
  if (activeCount >= 500) {
    res.status(503).json({ error: 'Registration is currently closed. Please try again later.' });
    return;
  }

  // Generate and save token
  const token = crypto.randomBytes(24).toString('hex');
  storeToken(token, ip);

  res.json({ token, message: 'Registration successful. Use this token to publish pages.' });
});

// === Admin Token Management (admin only) ===

app.get('/api/tokens', requireAdminAuth, (_req: Request, res: Response) => {
  const tokens = listAllTokens();
  res.json(tokens.map(t => ({
    id: t.id || t.token.slice(0, 12),
    token: t.token.slice(0, 8) + '...' + t.token.slice(-4),
    createdAt: t.createdAt,
    ip: t.ip,
    lastUsed: t.lastUsed,
    pagesCreated: t.pagesCreated,
    dailyPages: t.dailyPages,
    disabled: t.disabled,
  })));
});

app.post('/api/tokens/:token/revoke', requireAdminAuth, (req: Request, res: Response) => {
  const identifier = paramStr(req.params.token);
  // Try as full token first
  let ok = revokeToken(identifier);
  if (!ok) {
    // Try as short id
    const record = findTokenById(identifier);
    if (record) {
      ok = revokeToken(record.token);
    }
  }
  if (!ok) { res.status(404).json({ error: 'Token not found' }); return; }
  res.json({ revoked: true });
});

// === API Routes ===

app.post('/api/pages', requireAuth, async (req: Request, res: Response) => {
  try {
    let { html, spec, title, ttl, components, theme, deliver } = req.body;

    if (!spec && !html && components) {
      spec = { title: title || req.body.title, theme, components };
    }

    let finalHtml: string;
    let pageTitle: string = title;

    if (spec) {
      pageTitle = pageTitle || spec.title || 'Untitled';
      finalHtml = renderPage(spec as PageSpec);
    } else if (html) {
      pageTitle = pageTitle || 'Untitled';
      if (html.trim().toLowerCase().startsWith('<!doctype') || html.trim().toLowerCase().startsWith('<html')) {
        finalHtml = html;
      } else {
        finalHtml = renderRawPage(html, pageTitle);
      }
    } else {
      res.status(400).json({ error: 'Either "html" or "spec" is required' });
      return;
    }

    // Per-token daily page limit for registered tokens (50 pages/day)
    // Check before save so we can reject; increment after save so failures don't consume quota
    const authHeader = req.headers.authorization;
    let registeredToken: string | null = null;
    if (authHeader && authHeader.startsWith('Bearer ')) {
      const tkn = authHeader.slice(7);
      if (tkn !== API_TOKEN && !loadConfigTokens().includes(tkn)) {
        if (!checkDailyLimit(tkn, 50)) {
          res.status(429).json({ error: 'Daily page limit reached (50 pages/day). Try again tomorrow.' });
          return;
        }
        registeredToken = tkn;
      }
    }

    let result;
    try {
      result = savePage(finalHtml, { title: pageTitle, ttl, spec });
    } catch (saveErr: any) {
      if (saveErr.message?.includes('Page limit reached')) {
        res.status(507).json({ error: saveErr.message });
        return;
      }
      throw saveErr;
    }

    // Record usage only after successful save
    if (registeredToken) {
      recordUsage(registeredToken);
    }

    const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
    const pageUrl = `${baseUrl}/p/${result.id}`;

    const response: Record<string, any> = {
      id: result.id,
      url: pageUrl,
      title: pageTitle,
      meta: result.meta,
      formats: getPublicUrl() ? formatForAll(spec, pageUrl, pageTitle) : undefined,
    };

    if (deliver) {
      response.delivery = {
        platform: deliver.platform || 'unknown',
        success: false,
        error: '"deliver" is deprecated. Use response.formats for platform-specific summaries, then deliver via your agent/cc-connect.',
      };
    }

    res.json(response);
  } catch (err) {
    console.error('[api] Error creating page:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.get('/api/pages', requirePrivilegedAuth, (_req: Request, res: Response) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  res.json(pages.map(p => ({ ...p, url: `${baseUrl}/p/${p.id}` })));
});

app.get('/api/pages/:id', requirePrivilegedAuth, (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }
  const page = getPage(paramStr(req.params.id));
  if (!page) { res.status(404).json({ error: 'Page not found' }); return; }
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  const pageUrl = `${baseUrl}/p/${page.id}`;
  res.json({
    ...page.meta,
    id: page.id,
    url: pageUrl,
    formats: getPublicUrl() ? formatForAll(page.spec, pageUrl, page.meta?.title) : undefined,
  });
});

app.delete('/api/pages/:id', requirePrivilegedAuth, (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }
  const ok = deletePage(paramStr(req.params.id));
  if (!ok) { res.status(404).json({ error: 'Page not found' }); return; }
  res.json({ deleted: true });
});

// Deprecated: deliver endpoint returns formats instead
app.post('/api/pages/:id/deliver', requirePrivilegedAuth, (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }
  const page = getPage(paramStr(req.params.id), false);
  if (!page) { res.status(404).json({ error: 'Page not found' }); return; }
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  const pageUrl = `${baseUrl}/p/${page.id}`;
  res.json({
    platform: req.body?.platform || 'unknown',
    success: false,
    error: 'Delivery is deprecated. Use the "formats" field below to deliver via your agent.',
    formats: formatForAll(page.spec, pageUrl, page.meta?.title),
  });
});

app.get('/api/platforms', requirePrivilegedAuth, (_req: Request, res: Response) => {
  res.json(listPlatforms());
});

app.get('/api/status', requireAuth, (_req: Request, res: Response) => {
  res.json({
    status: 'running',
    port: PORT,
    publicUrl: getPublicUrl(),
    pages: listPages().length,
    platforms: listPlatforms(),
  });
});

// === Page Rendering (PUBLIC) ===

app.get('/p/:id', (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).send('Invalid page ID'); return; }

  const page = getPage(paramStr(req.params.id));
  if (!page) {
    res.status(404).send(renderRawPage(`
      <div class="flex items-center justify-center min-h-[80vh]">
        <div class="text-center">
          <div class="text-6xl mb-4">404</div>
          <h1 class="text-2xl font-bold text-gray-900 dark:text-white mb-2">Page Not Found</h1>
          <p class="text-gray-500 dark:text-gray-400">This page may have expired or been deleted.</p>
        </div>
      </div>
    `, '404 - Not Found'));
    return;
  }

  res.header('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net",
    "style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://fonts.googleapis.com",
    "img-src 'self' data: https:",
    "media-src 'self' https:",
    "font-src 'self' https: data:",
    "connect-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ].join('; '));

  res.type('html').send(page.html);
});

app.get('/', requirePrivilegedAuth, (_req: Request, res: Response) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;

  const pageListHtml = pages.length === 0
    ? `<p class="text-gray-500 dark:text-gray-400 text-center py-8">No pages yet. Create one via the API or CLI.</p>`
    : `<div class="space-y-3">
        ${pages.map(p => `
          <a href="/p/${p.id}" class="block bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 hover:shadow-md transition-shadow">
            <div class="flex justify-between items-center">
              <div>
                <h3 class="font-semibold text-gray-900 dark:text-white">${escHtml(p.title)}</h3>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">${new Date(p.createdAt).toLocaleString()} · ${p.views} views</p>
              </div>
              <span class="text-sm text-blue-600 dark:text-blue-400">/p/${p.id}</span>
            </div>
          </a>
        `).join('')}
      </div>`;

  res.type('html').send(renderRawPage(`
    <div class="max-w-3xl mx-auto px-4 py-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 dark:text-white">Claw2UI</h1>
        <p class="text-gray-500 dark:text-gray-400 mt-2">Agent-to-UI Bridge · ${pages.length} pages</p>
      </div>
      ${pageListHtml}
    </div>
  `, 'Claw2UI'));
});

app.use((_req: Request, res: Response) => {
  res.status(404).json({ error: 'Not found' });
});

// === Start Server ===
async function main(): Promise<void> {
  console.log(`[claw2ui] API token: ${API_TOKEN.slice(0, 8)}...`);
  console.log(`[claw2ui] Token file: ${TOKEN_FILE}`);

  const server = app.listen(PORT, '127.0.0.1', () => {
    console.log(`[claw2ui] Server running on http://127.0.0.1:${PORT} (localhost only)`);
  });

  if (!NO_TUNNEL) {
    try {
      const url = await startTunnel(PORT);
      console.log(`[claw2ui] Public URL: ${url}`);
      const urlFile = path.join(__dirname, '..', '.public-url');
      fs.writeFileSync(urlFile, url);
    } catch (err: any) {
      console.error('[claw2ui] Tunnel failed:', err.message);
    }
  }

  process.on('SIGTERM', () => {
    console.log('[claw2ui] Shutting down...');
    stopTunnel();
    server.close();
  });
  process.on('SIGINT', () => {
    console.log('[claw2ui] Shutting down...');
    stopTunnel();
    server.close();
    process.exit(0);
  });
}

main();
