#!/usr/bin/env node
/**
 * ClawBoard Server
 *
 * An Agent-to-UI bridge that serves interactive pages generated by AI agents.
 * Pages are accessible via tunnel URL even without a public IP.
 *
 * Security:
 *   - API endpoints require Bearer token (auto-generated on first run)
 *   - Page viewing (/p/:id) is public (by design - shared via URL)
 *   - Page IDs are cryptographically random (nanoid)
 *   - Home page / page listing requires auth
 *   - Rate limiting on all endpoints
 *
 * API:
 *   POST /api/pages          - Create a page (JSON body: { html?, spec?, title?, ttl? })
 *   GET  /api/pages          - List all pages
 *   GET  /api/pages/:id      - Get page metadata
 *   DELETE /api/pages/:id    - Delete a page
 *   GET  /api/status         - Server status & public URL
 *   GET  /p/:id              - View a rendered page (public, no auth)
 */
const express = require('express');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { savePage, getPage, listPages, deletePage } = require('./store');
const { renderPage, renderRawPage } = require('./renderer');
const { startTunnel, getPublicUrl, stopTunnel } = require('./tunnel');

const PORT = parseInt(process.env.CLAWBOARD_PORT || '9800', 10);
const NO_TUNNEL = process.env.CLAWBOARD_NO_TUNNEL === '1';

// === Security: API Token ===
const TOKEN_FILE = path.join(__dirname, '..', '.api-token');

function getOrCreateToken() {
  if (process.env.CLAWBOARD_TOKEN) return process.env.CLAWBOARD_TOKEN;
  if (fs.existsSync(TOKEN_FILE)) return fs.readFileSync(TOKEN_FILE, 'utf-8').trim();
  const token = crypto.randomBytes(32).toString('hex');
  fs.writeFileSync(TOKEN_FILE, token, { mode: 0o600 });
  return token;
}

const API_TOKEN = getOrCreateToken();

/**
 * Auth middleware - checks Bearer token or localhost origin
 * Localhost requests (from the same machine) are allowed without token,
 * since the agent and server run on the same host.
 */
function requireAuth(req, res, next) {
  // Allow requests from localhost without token (agent runs locally)
  const ip = req.ip || req.connection.remoteAddress || '';
  const isLocal = ip === '127.0.0.1' || ip === '::1' || ip === '::ffff:127.0.0.1';
  if (isLocal) return next();

  // Check Bearer token for remote requests
  const auth = req.headers.authorization;
  if (auth && auth.startsWith('Bearer ') && auth.slice(7) === API_TOKEN) {
    return next();
  }

  res.status(401).json({ error: 'Unauthorized. Provide Authorization: Bearer <token>' });
}

// === Rate Limiting ===
const rateLimitMap = new Map();
const RATE_LIMIT_WINDOW = 60_000; // 1 minute
const RATE_LIMIT_MAX = 30; // max requests per window per IP

function rateLimit(req, res, next) {
  const ip = req.ip || req.connection.remoteAddress || '';
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now - entry.start > RATE_LIMIT_WINDOW) {
    rateLimitMap.set(ip, { start: now, count: 1 });
    return next();
  }

  entry.count++;
  if (entry.count > RATE_LIMIT_MAX) {
    return res.status(429).json({ error: 'Too many requests. Try again later.' });
  }
  next();
}

// Clean up rate limit map periodically
setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of rateLimitMap) {
    if (now - entry.start > RATE_LIMIT_WINDOW) rateLimitMap.delete(ip);
  }
}, RATE_LIMIT_WINDOW);

// === App Setup ===
const app = express();

// Trust proxy (cloudflared forwards via proxy)
app.set('trust proxy', 'loopback');

app.use(express.json({ limit: '2mb' })); // Reduced from 10mb
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(rateLimit);

// Security headers
app.use((req, res, next) => {
  res.header('X-Content-Type-Options', 'nosniff');
  res.header('X-Frame-Options', 'DENY');
  res.header('Referrer-Policy', 'no-referrer');
  next();
});

// CORS - only allow localhost origins for API
app.use((req, res, next) => {
  const origin = req.headers.origin || '';
  if (origin.startsWith('http://localhost') || origin.startsWith('http://127.0.0.1')) {
    res.header('Access-Control-Allow-Origin', origin);
  }
  res.header('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});

// === API Routes (all require auth) ===

// Create a page
app.post('/api/pages', requireAuth, (req, res) => {
  try {
    let { html, spec, title, ttl, type, components, theme } = req.body;

    // Auto-detect: if body has "components" at top level, treat as spec
    if (!spec && !html && components) {
      spec = { title: title || req.body.title, theme, components };
    }

    let finalHtml;
    let pageTitle = title;

    if (spec) {
      // A2UI-style component spec - safe (declarative, no raw JS)
      pageTitle = pageTitle || spec.title || 'Untitled';
      finalHtml = renderPage(spec);
    } else if (html) {
      // Raw HTML - add CSP to mitigate XSS
      pageTitle = pageTitle || 'Untitled';
      if (html.trim().toLowerCase().startsWith('<!doctype') || html.trim().toLowerCase().startsWith('<html')) {
        finalHtml = html;
      } else {
        finalHtml = renderRawPage(html, pageTitle);
      }
    } else {
      return res.status(400).json({ error: 'Either "html" or "spec" is required' });
    }

    const result = savePage(finalHtml, { title: pageTitle, ttl, type });
    const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
    const pageUrl = `${baseUrl}/p/${result.id}`;

    res.json({
      id: result.id,
      url: pageUrl,
      title: pageTitle,
      meta: result.meta,
    });
  } catch (err) {
    console.error('[api] Error creating page:', err);
    res.status(500).json({ error: 'Internal server error' }); // Don't leak error details
  }
});

// List pages (auth required)
app.get('/api/pages', requireAuth, (req, res) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  res.json(pages.map(p => ({ ...p, url: `${baseUrl}/p/${p.id}` })));
});

// Get page meta (auth required)
app.get('/api/pages/:id', requireAuth, (req, res) => {
  const page = getPage(req.params.id);
  if (!page) return res.status(404).json({ error: 'Page not found' });
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  res.json({ ...page.meta, id: page.id, url: `${baseUrl}/p/${page.id}` });
});

// Delete page (auth required)
app.delete('/api/pages/:id', requireAuth, (req, res) => {
  const ok = deletePage(req.params.id);
  if (!ok) return res.status(404).json({ error: 'Page not found' });
  res.json({ deleted: true });
});

// Server status (auth required)
app.get('/api/status', requireAuth, (req, res) => {
  res.json({
    status: 'running',
    port: PORT,
    publicUrl: getPublicUrl(),
    pages: listPages().length,
  });
});

// === Page Rendering (PUBLIC - no auth) ===

// View a page - public by design (shared via URL with random ID)
app.get('/p/:id', (req, res) => {
  // Validate ID format (nanoid: alphanumeric + _-)
  if (!/^[A-Za-z0-9_-]{5,30}$/.test(req.params.id)) {
    return res.status(400).send('Invalid page ID');
  }

  const page = getPage(req.params.id);
  if (!page) {
    return res.status(404).send(renderRawPage(`
      <div class="flex items-center justify-center min-h-[80vh]">
        <div class="text-center">
          <div class="text-6xl mb-4">404</div>
          <h1 class="text-2xl font-bold text-gray-900 dark:text-white mb-2">Page Not Found</h1>
          <p class="text-gray-500 dark:text-gray-400">This page may have expired or been deleted.</p>
        </div>
      </div>
    `, '404 - Not Found'));
  }

  // Add Content-Security-Policy for rendered pages
  // Allow Tailwind CDN, Chart.js, Alpine.js but block inline event handlers from unknown sources
  res.header('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net",
    "style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com",
    "img-src 'self' data: https:",
    "font-src 'self' https:",
    "connect-src 'self'",
    "frame-ancestors 'none'",
  ].join('; '));

  res.type('html').send(page.html);
});

// Home page - requires auth (don't expose page listing to public)
app.get('/', requireAuth, (req, res) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;

  const pageListHtml = pages.length === 0
    ? `<p class="text-gray-500 dark:text-gray-400 text-center py-8">No pages yet. Create one via the API or CLI.</p>`
    : `<div class="space-y-3">
        ${pages.map(p => `
          <a href="/p/${p.id}" class="block bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 hover:shadow-md transition-shadow">
            <div class="flex justify-between items-center">
              <div>
                <h3 class="font-semibold text-gray-900 dark:text-white">${escHtml(p.title)}</h3>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">${new Date(p.createdAt).toLocaleString()} · ${p.views} views</p>
              </div>
              <span class="text-sm text-blue-600 dark:text-blue-400">/p/${p.id}</span>
            </div>
          </a>
        `).join('')}
      </div>`;

  res.type('html').send(renderRawPage(`
    <div class="max-w-3xl mx-auto px-4 py-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 dark:text-white">ClawBoard</h1>
        <p class="text-gray-500 dark:text-gray-400 mt-2">Agent-to-UI Bridge · ${pages.length} pages</p>
      </div>
      ${pageListHtml}
    </div>
  `, 'ClawBoard'));
});

// Catch-all: 404 for unknown routes
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// === Start Server ===
async function main() {
  console.log(`[clawboard] API token: ${API_TOKEN.slice(0, 8)}...`);
  console.log(`[clawboard] Token file: ${TOKEN_FILE}`);

  const server = app.listen(PORT, '127.0.0.1', () => {
    console.log(`[clawboard] Server running on http://127.0.0.1:${PORT} (localhost only)`);
  });

  if (!NO_TUNNEL) {
    try {
      const url = await startTunnel(PORT);
      console.log(`[clawboard] Public URL: ${url}`);
      const urlFile = path.join(__dirname, '..', '.public-url');
      fs.writeFileSync(urlFile, url);
    } catch (err) {
      console.error('[clawboard] Tunnel failed:', err.message);
    }
  }

  // Graceful shutdown
  process.on('SIGTERM', () => {
    console.log('[clawboard] Shutting down...');
    stopTunnel();
    server.close();
  });
  process.on('SIGINT', () => {
    console.log('[clawboard] Shutting down...');
    stopTunnel();
    server.close();
    process.exit(0);
  });
}

main();
