#!/usr/bin/env node
/**
 * ClawBoard Server
 *
 * An Agent-to-UI bridge that serves interactive pages generated by AI agents.
 * Pages are accessible via tunnel URL even without a public IP.
 *
 * API:
 *   POST /api/pages          - Create a page (JSON body: { html?, spec?, title?, ttl?, deliver? })
 *   GET  /api/pages          - List all pages
 *   GET  /api/pages/:id      - Get page metadata
 *   DELETE /api/pages/:id    - Delete a page
 *   POST /api/pages/:id/deliver - Deliver page to a platform (e.g., Telegram)
 *   GET  /api/platforms      - List registered platforms and their config status
 *   GET  /api/status         - Server status & public URL
 *   GET  /p/:id              - View a rendered page (public, no auth)
 */
import express, { Request, Response, NextFunction } from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { savePage, getPage, listPages, deletePage } from './store';
import { renderPage, renderRawPage } from './renderer';
import { startTunnel, getPublicUrl, stopTunnel } from './tunnel';
import { formatForPlatform, deliverToPlatform, listPlatforms, formatForAll } from './platforms';
import type { PageSpec } from './types';

const PORT = parseInt(process.env.CLAWBOARD_PORT || '9800', 10);
const NO_TUNNEL = process.env.CLAWBOARD_NO_TUNNEL === '1';

// === Security: API Token ===
const TOKEN_FILE = path.join(__dirname, '..', '.api-token');

function getOrCreateToken(): string {
  if (process.env.CLAWBOARD_TOKEN) return process.env.CLAWBOARD_TOKEN;
  if (fs.existsSync(TOKEN_FILE)) return fs.readFileSync(TOKEN_FILE, 'utf-8').trim();
  const token = crypto.randomBytes(32).toString('hex');
  fs.writeFileSync(TOKEN_FILE, token, { mode: 0o600 });
  return token;
}

const API_TOKEN = getOrCreateToken();

/**
 * Auth middleware - checks Bearer token or localhost origin
 */
function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const ip = req.ip || '';
  const isLocal = ip === '127.0.0.1' || ip === '::1' || ip === '::ffff:127.0.0.1';
  if (isLocal) { next(); return; }

  const auth = req.headers.authorization;
  if (auth && auth.startsWith('Bearer ') && auth.slice(7) === API_TOKEN) {
    next(); return;
  }

  res.status(401).json({ error: 'Unauthorized. Provide Authorization: Bearer <token>' });
}

// === Rate Limiting ===
interface RateLimitEntry {
  start: number;
  count: number;
}

const rateLimitMap = new Map<string, RateLimitEntry>();
const RATE_LIMIT_WINDOW = 60_000;
const RATE_LIMIT_MAX = 30;

function rateLimit(req: Request, res: Response, next: NextFunction): void {
  const ip = req.ip || '';
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now - entry.start > RATE_LIMIT_WINDOW) {
    rateLimitMap.set(ip, { start: now, count: 1 });
    next(); return;
  }

  entry.count++;
  if (entry.count > RATE_LIMIT_MAX) {
    res.status(429).json({ error: 'Too many requests. Try again later.' });
    return;
  }
  next();
}

setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of rateLimitMap) {
    if (now - entry.start > RATE_LIMIT_WINDOW) rateLimitMap.delete(ip);
  }
}, RATE_LIMIT_WINDOW);

// === App Setup ===
const app = express();

app.set('trust proxy', 'loopback');

app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(rateLimit);

// Security headers
app.use((_req: Request, res: Response, next: NextFunction) => {
  res.header('X-Content-Type-Options', 'nosniff');
  res.header('X-Frame-Options', 'DENY');
  res.header('Referrer-Policy', 'no-referrer');
  next();
});

// CORS
app.use((req: Request, res: Response, next: NextFunction) => {
  const origin = req.headers.origin || '';
  if (origin.startsWith('http://localhost') || origin.startsWith('http://127.0.0.1')) {
    res.header('Access-Control-Allow-Origin', origin);
  }
  res.header('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') { res.sendStatus(200); return; }
  next();
});

/** Validate page ID format - prevent path traversal */
function isValidPageId(id: string): boolean {
  return /^[A-Za-z0-9_-]{5,30}$/.test(id);
}

/** Extract route param as string (Express 5 params can be string | string[]) */
function paramStr(val: string | string[] | undefined): string {
  if (Array.isArray(val)) return val[0] || '';
  return val || '';
}

function escHtml(s: string): string {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// === API Routes ===

app.post('/api/pages', requireAuth, async (req: Request, res: Response) => {
  try {
    let { html, spec, title, ttl, type, components, theme, deliver } = req.body;

    if (!spec && !html && components) {
      spec = { title: title || req.body.title, theme, components };
    }

    let finalHtml: string;
    let pageTitle: string = title;

    if (spec) {
      pageTitle = pageTitle || spec.title || 'Untitled';
      finalHtml = renderPage(spec as PageSpec);
    } else if (html) {
      pageTitle = pageTitle || 'Untitled';
      if (html.trim().toLowerCase().startsWith('<!doctype') || html.trim().toLowerCase().startsWith('<html')) {
        finalHtml = html;
      } else {
        finalHtml = renderRawPage(html, pageTitle);
      }
    } else {
      res.status(400).json({ error: 'Either "html" or "spec" is required' });
      return;
    }

    const result = savePage(finalHtml, { title: pageTitle, ttl, type, spec });
    const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
    const pageUrl = `${baseUrl}/p/${result.id}`;

    const response: Record<string, any> = {
      id: result.id,
      url: pageUrl,
      title: pageTitle,
      meta: result.meta,
    };

    response.formats = formatForAll(spec, pageUrl, pageTitle);

    if (deliver && deliver.platform) {
      const platform: string = deliver.platform;
      if (!getPublicUrl()) {
        response.delivery = { platform, success: false, error: 'No public URL available. Start tunnel first.' };
      } else {
        const message = formatForPlatform(platform, spec, pageUrl, pageTitle);
        if (message) {
          const deliveryResult = await deliverToPlatform(platform, message, deliver);
          response.delivery = { platform, ...deliveryResult };
        } else {
          response.delivery = { platform, success: false, error: `Unknown platform: ${platform}` };
        }
      }
    }

    res.json(response);
  } catch (err) {
    console.error('[api] Error creating page:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.get('/api/pages', requireAuth, (_req: Request, res: Response) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  res.json(pages.map(p => ({ ...p, url: `${baseUrl}/p/${p.id}` })));
});

app.get('/api/pages/:id', requireAuth, (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }
  const page = getPage(paramStr(req.params.id));
  if (!page) { res.status(404).json({ error: 'Page not found' }); return; }
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
  res.json({ ...page.meta, id: page.id, url: `${baseUrl}/p/${page.id}` });
});

app.delete('/api/pages/:id', requireAuth, (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }
  const ok = deletePage(paramStr(req.params.id));
  if (!ok) { res.status(404).json({ error: 'Page not found' }); return; }
  res.json({ deleted: true });
});

app.post('/api/pages/:id/deliver', requireAuth, async (req: Request, res: Response) => {
  try {
    if (!isValidPageId(paramStr(req.params.id))) { res.status(400).json({ error: 'Invalid page ID' }); return; }

    const page = getPage(paramStr(req.params.id), false);
    if (!page) { res.status(404).json({ error: 'Page not found' }); return; }

    const { platform, chatId, botToken, proxy } = req.body;
    if (!platform) { res.status(400).json({ error: '"platform" is required (e.g., "telegram")' }); return; }

    const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;
    const pageUrl = `${baseUrl}/p/${page.id}`;

    const message = formatForPlatform(platform, page.spec, pageUrl, page.meta?.title);
    if (!message) { res.status(400).json({ error: `Unknown platform: ${platform}` }); return; }

    const result = await deliverToPlatform(platform, message, { chatId, botToken, proxy });
    res.json({ platform, ...result });
  } catch (err) {
    console.error('[api] Error delivering page:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.get('/api/platforms', requireAuth, (_req: Request, res: Response) => {
  res.json(listPlatforms());
});

app.get('/api/status', requireAuth, (_req: Request, res: Response) => {
  res.json({
    status: 'running',
    port: PORT,
    publicUrl: getPublicUrl(),
    pages: listPages().length,
    platforms: listPlatforms(),
  });
});

// === Page Rendering (PUBLIC) ===

app.get('/p/:id', (req: Request, res: Response) => {
  if (!isValidPageId(paramStr(req.params.id))) { res.status(400).send('Invalid page ID'); return; }

  const page = getPage(paramStr(req.params.id));
  if (!page) {
    res.status(404).send(renderRawPage(`
      <div class="flex items-center justify-center min-h-[80vh]">
        <div class="text-center">
          <div class="text-6xl mb-4">404</div>
          <h1 class="text-2xl font-bold text-gray-900 dark:text-white mb-2">Page Not Found</h1>
          <p class="text-gray-500 dark:text-gray-400">This page may have expired or been deleted.</p>
        </div>
      </div>
    `, '404 - Not Found'));
    return;
  }

  res.header('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net",
    "style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com",
    "img-src 'self' data: https:",
    "font-src 'self' https:",
    "connect-src 'self'",
    "frame-ancestors 'none'",
  ].join('; '));

  res.type('html').send(page.html);
});

app.get('/', requireAuth, (_req: Request, res: Response) => {
  const pages = listPages();
  const baseUrl = getPublicUrl() || `http://localhost:${PORT}`;

  const pageListHtml = pages.length === 0
    ? `<p class="text-gray-500 dark:text-gray-400 text-center py-8">No pages yet. Create one via the API or CLI.</p>`
    : `<div class="space-y-3">
        ${pages.map(p => `
          <a href="/p/${p.id}" class="block bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 hover:shadow-md transition-shadow">
            <div class="flex justify-between items-center">
              <div>
                <h3 class="font-semibold text-gray-900 dark:text-white">${escHtml(p.title)}</h3>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">${new Date(p.createdAt).toLocaleString()} · ${p.views} views</p>
              </div>
              <span class="text-sm text-blue-600 dark:text-blue-400">/p/${p.id}</span>
            </div>
          </a>
        `).join('')}
      </div>`;

  res.type('html').send(renderRawPage(`
    <div class="max-w-3xl mx-auto px-4 py-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 dark:text-white">ClawBoard</h1>
        <p class="text-gray-500 dark:text-gray-400 mt-2">Agent-to-UI Bridge · ${pages.length} pages</p>
      </div>
      ${pageListHtml}
    </div>
  `, 'ClawBoard'));
});

app.use((_req: Request, res: Response) => {
  res.status(404).json({ error: 'Not found' });
});

// === Start Server ===
async function main(): Promise<void> {
  console.log(`[clawboard] API token: ${API_TOKEN.slice(0, 8)}...`);
  console.log(`[clawboard] Token file: ${TOKEN_FILE}`);

  const server = app.listen(PORT, '127.0.0.1', () => {
    console.log(`[clawboard] Server running on http://127.0.0.1:${PORT} (localhost only)`);
  });

  if (!NO_TUNNEL) {
    try {
      const url = await startTunnel(PORT);
      console.log(`[clawboard] Public URL: ${url}`);
      const urlFile = path.join(__dirname, '..', '.public-url');
      fs.writeFileSync(urlFile, url);
    } catch (err: any) {
      console.error('[clawboard] Tunnel failed:', err.message);
    }
  }

  process.on('SIGTERM', () => {
    console.log('[clawboard] Shutting down...');
    stopTunnel();
    server.close();
  });
  process.on('SIGINT', () => {
    console.log('[clawboard] Shutting down...');
    stopTunnel();
    server.close();
    process.exit(0);
  });
}

main();
